"use client";

import { useClerk } from "@clerk/nextjs";
import { useEffect, useMemo, useState } from "react";

type Staff = { id: string; name: string; email: string; phone: string | null; role: string; active: boolean };
type Shift = { id: string; templateId?: string | null; date: string; title: string; startsAt: string; endsAt: string; assignee: string; assignedStaff?: { id: string; name: string }[]; requiredStaff: number; assignedCount: number; status: string };
type ShiftTemplate = { id: string; title: string; dayOfWeek: number; startsAt: string; endsAt: string; requiredStaff: number };
type PayPeriod = { start: string; end: string; dueDate: string; defaultDueDate: string };
type Snapshot = { demo: boolean; viewer: { name: string; email: string; phone: string | null; role: string }; staff: Staff[]; shifts: Shift[]; templates?: ShiftTemplate[]; swaps: { id: string; requester: string; shift: string; recipient: string; status: string }[]; availability: { staff: string; note: string }[]; payPeriod: PayPeriod; periodOffset?: number };

const tabs = ["Dashboard", "Schedule", "Staff", "Availability", "Open shifts", "Swaps", "Hours"] as const;
type Tab = (typeof tabs)[number];

function readableDate(date: string) { return new Intl.DateTimeFormat(undefined, { weekday: "short", month: "short", day: "numeric" }).format(new Date(`${date}T12:00:00`)); }
function readableLongDate(date: string) { return new Intl.DateTimeFormat(undefined, { weekday: "long", month: "long", day: "numeric" }).format(new Date(`${date}T12:00:00`)); }
function duration(start: string, end: string) { const [a, b] = [start, end].map((value) => { const [hour, minute] = value.split(":").map(Number); return hour + minute / 60; }); return Math.max(0, b - a); }

export default function Scheduler() {
  const [tab, setTab] = useState<Tab>("Dashboard"); const [data, setData] = useState<Snapshot | null>(null); const [notice, setNotice] = useState(""); const [periodOffset, setPeriodOffset] = useState(0);
  const refresh = () => fetch(`/api/schedule?periodOffset=${periodOffset}`).then((res) => res.json()).then((body) => setData(body)).catch(() => setNotice("Could not load the schedule."));
  useEffect(() => { refresh(); }, [periodOffset]);
  const openShifts = data?.shifts.filter((shift) => shift.status === "open") ?? [];
  const scheduledHours = useMemo(() => (data?.shifts ?? []).reduce((total, shift) => total + duration(shift.startsAt, shift.endsAt) * shift.assignedCount, 0), [data]);
  async function api(path: string, method: string, body?: unknown) {
    if (data?.demo) { setNotice("Preview mode: sign in to save this change."); return; }
    try {
      const response = await fetch(path, { method, headers: { "content-type": "application/json" }, body: body ? JSON.stringify(body) : undefined });
      const payload = await response.json().catch(() => ({})); setNotice(payload.error || payload.message || (payload.ok ? "Saved." : "Something went wrong.")); if (payload.ok) await refresh();
    } catch { setNotice("That request could not be completed. Please try again."); }
  }
  if (!data) return <main className="loading">Loading the schedule…</main>;
  return <main>
    <header><div className="topbar"><div><strong>Seal Beach Aquatics Schedule</strong><span>{data.demo ? "Interactive preview" : `${data.viewer.role} view`}</span></div>{data.demo ? <a href="/sign-in">Sign in</a> : <div style={{ display: "flex", alignItems: "center", gap: "10px" }}><span>Signed in as {data.viewer.name}</span><SignOutButton /></div>}</div></header>
    <section className="wrap"><div className="title-row"><div><p className="eyebrow">Operations center</p><h1>Clear coverage, calmer days.</h1><p className="muted">Plan the pay period, coordinate changes, and keep every lifeguard in the loop.</p></div>{data.demo && <div className="preview-note">Sign in to use the secure staff schedule and save changes.</div>}</div>
      <nav className="tabs" aria-label="Scheduling areas">{tabs.map((item) => <button key={item} className={tab === item ? "tab active" : "tab"} onClick={() => setTab(item)}>{item}</button>)}</nav>
      {notice && <p className="notice">{notice}<button onClick={() => setNotice("")} aria-label="Dismiss">×</button></p>}
      {tab === "Dashboard" && <Dashboard data={data} openCount={openShifts.length} hours={scheduledHours} setTab={setTab} api={api} />}
      {tab === "Schedule" && <Schedule data={data} api={api} periodOffset={periodOffset} setPeriodOffset={setPeriodOffset} />}
      {tab === "Staff" && <Directory data={data} api={api} />}
      {tab === "Availability" && <Availability data={data} api={api} />}
      {tab === "Open shifts" && <OpenShifts shifts={openShifts} api={api} />}
      {tab === "Swaps" && <Swaps data={data} api={api} />}
      {tab === "Hours" && <Hours data={data} scheduledHours={scheduledHours} />}
    </section>
  </main>;
}

function SignOutButton() {
  const { signOut } = useClerk();
  return <button className="secondary small-button" onClick={() => signOut({ redirectUrl: "/" })}>Sign out</button>;
}

function Dashboard({ data, openCount, hours, setTab, api }: { data: Snapshot; openCount: number; hours: number; setTab: (tab: Tab) => void; api: (path: string, method: string, body?: unknown) => Promise<void> }) { return <><div className="metrics"><Metric label="Active staff" value={data.staff.length} /><Metric label="Open shifts" value={openCount} /><Metric label="Pending swaps" value={data.swaps.filter((item) => item.status === "pending").length} /><Metric label="Scheduled this pay period" value={`${hours} hrs`} /></div><section className="card pay-period-card"><div><p className="eyebrow">Current pay period</p><h2>{readableDate(data.payPeriod.start)} – {readableDate(data.payPeriod.end)}</h2><p className="muted">Two weeks, Sunday through Saturday. Scheduled hours and coverage include the entire pay period.</p></div><div className="due-date"><span>Timesheets due</span><strong>{readableLongDate(data.payPeriod.dueDate)}</strong>{data.payPeriod.dueDate !== data.payPeriod.defaultDueDate && <em>Manager-adjusted deadline</em>}{data.viewer.role === "manager" && <DueDateForm payPeriod={data.payPeriod} api={api} />}</div></section><section className="card action-card"><div><p className="eyebrow">Manager dashboard</p><h2>Pay period at a glance</h2><p className="muted">Review coverage gaps, availability conflicts, and staff requests from one place.</p></div><button onClick={() => setTab("Schedule")}>Open schedule builder</button></section><section className="two-col"><article className="card"><h2>Needs attention</h2>{openCount ? <p>{openCount} open shift{openCount === 1 ? "" : "s"} still need coverage.</p> : <p>All scheduled shifts are covered.</p>}<button className="secondary" onClick={() => setTab("Open shifts")}>Review open shifts</button></article><article className="card"><h2>Availability notes</h2>{data.availability.map((item) => <p className="list-item" key={`${item.staff}-${item.note}`}><strong>{item.staff}</strong><span>{item.note}</span></p>)}</article></section></> }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="metric card"><span>{label}</span><strong>{value}</strong></div>; }
function DueDateForm({ payPeriod, api }: { payPeriod: PayPeriod; api: (path: string, method: string, body?: unknown) => Promise<void> }) { const [editing, setEditing] = useState(false); const [dueDate, setDueDate] = useState(payPeriod.dueDate); useEffect(() => setDueDate(payPeriod.dueDate), [payPeriod.dueDate]); if (!editing) return <button className="secondary small-button" onClick={() => setEditing(true)}>Change deadline</button>; return <form className="due-date-form" onSubmit={(event) => { event.preventDefault(); api("/api/pay-period", "PATCH", { dueDate }); setEditing(false); }}><label>Due date<input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} required /></label><button type="submit" className="small-button">Save</button><button type="button" className="secondary small-button" onClick={() => { setDueDate(payPeriod.dueDate); setEditing(false); }}>Cancel</button></form> }
function Schedule({ data, api, periodOffset, setPeriodOffset }: { data: Snapshot; api: (path: string, method: string, body?: unknown) => Promise<void>; periodOffset: number; setPeriodOffset: (offset: number) => void }) {
  const byDate = Object.groupBy(data.shifts, (shift) => shift.date);
  const dates = Array.from({ length: 14 }, (_, index) => { const date = new Date(`${data.payPeriod.start}T12:00:00`); date.setDate(date.getDate() + index); return date.toISOString().slice(0, 10); });
  const manager = data.viewer.role === "manager";
  return <>
    <section className="card schedule-head"><div><p className="eyebrow">Manager schedule builder</p><h2>Pay-period schedule</h2><p className="muted">{readableDate(data.payPeriod.start)} through {readableDate(data.payPeriod.end)} · Sunday–Saturday, two-week period.</p>{manager && <p className="builder-tip">Standard coverage shifts are ready in each day below. Each shift has two staff positions—choose an employee for each one.</p>}<div className="schedule-controls"><button className="secondary" onClick={() => setPeriodOffset(periodOffset - 1)} disabled={periodOffset <= -4}>Previous pay period</button><button className="secondary" onClick={() => setPeriodOffset(0)} disabled={periodOffset === 0}>Current pay period</button>{manager && <button onClick={() => window.print()}>Print roster</button>}</div></div>{manager && <ShiftForm staff={data.staff} onSubmit={(body) => api("/api/shifts", "POST", body)} />}</section>
    <section className="schedule-grid">{dates.map((date) => {
      const dayShifts = byDate[date] ?? [];
      const weekday = new Date(`${date}T12:00:00`).getDay();
      const templatesForDay = (data.templates ?? []).filter((template) => template.dayOfWeek === weekday);
      return <article className="day card" key={date}><h3>{readableDate(date)}</h3>{dayShifts.filter((shift) => !manager || !shift.templateId).map((shift) => <ShiftCard api={api} manager={manager} key={shift.id} shift={shift} />)}{manager && templatesForDay.map((template) => { const matchingShift = dayShifts.find((shift) => shift.templateId === template.id || (shift.title === template.title && shift.startsAt === template.startsAt && shift.endsAt === template.endsAt)); return <StandardShiftSlots key={template.id} template={template} date={date} staff={data.staff} api={api} shift={matchingShift} />; })}</article>;
    })}</section>{manager && <PrintRoster staff={data.staff} shifts={data.shifts} dates={dates} payPeriod={data.payPeriod} />}</>
}

function ShiftCard({ shift, manager, api }: { shift: Shift; manager: boolean; api: (path: string, method: string, body?: unknown) => Promise<void> }) {
  return <div className={shift.status === "open" ? "shift open" : "shift"}><strong>{shift.title}</strong><span>{shift.startsAt}–{shift.endsAt} · {duration(shift.startsAt, shift.endsAt)} hrs</span><b>{shift.assignedCount} of {shift.requiredStaff} assigned · {shift.assignee}</b>{manager && <ShiftTimeEditor shift={shift} api={api} />}{shift.status === "open" && <button className="secondary" onClick={() => api(`/api/open-shifts/${shift.id}/claim`, "POST")}>Claim shift</button>}</div>;
}

function StandardShiftSlots({ template, date, staff, api, shift }: { template: ShiftTemplate; date: string; staff: Staff[]; api: (path: string, method: string, body?: unknown) => Promise<void>; shift?: Shift }) {
  const [selections, setSelections] = useState(["", ""]); const [saving, setSaving] = useState(false);
  const assignedNames = shift?.assignedStaff?.map((person) => person.name) ?? (shift?.assignee === "Open" || !shift ? [] : shift.assignee.split(", "));
  useEffect(() => { setSelections(["", ""]); setSaving(false); }, [shift?.id, shift?.assignedCount]);
  async function assign(position: number) { const staffId = selections[position]; if (!staffId || saving) return; setSaving(true); await api("/api/shifts", "POST", shift ? { action: "assignToShift", shiftId: shift.id, staffId } : { action: "assignTemplate", templateId: template.id, date, staffId }); setSelections((current) => current.map((value, index) => index === position ? "" : value)); setSaving(false); }
  return <section className="shift-slots"><div className="shift-slots-heading"><strong>{template.title}</strong><span>{template.startsAt}–{template.endsAt} · {duration(template.startsAt, template.endsAt)} hrs · {shift?.assignedCount ?? 0} of {template.requiredStaff} assigned</span></div>{Array.from({ length: template.requiredStaff }, (_, position) => { const assignedName = assignedNames[position]; return <div className="assignment-row" key={position}>{assignedName ? <p className="assignment-filled"><strong>Position {position + 1}</strong><span>{assignedName}</span></p> : <><label className="assignment-control"><span>Position {position + 1}</span><select aria-label={`Assign ${template.title} position ${position + 1}`} value={selections[position] ?? ""} onChange={(event) => setSelections((current) => current.map((value, index) => index === position ? event.target.value : value))} disabled={saving}><option value="">Assign a staff member…</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.name}{person.role === "manager" ? " (Manager)" : ""}</option>)}</select></label><button type="button" onClick={() => assign(position)} disabled={saving || !selections[position]}>Assign</button></>}</div>; })}{shift && <ShiftTimeEditor shift={shift} api={api} />}</section>;
}

function ShiftTimeEditor({ shift, api }: { shift: Shift; api: (path: string, method: string, body?: unknown) => Promise<void> }) {
  const [editing, setEditing] = useState(false); const [startsAt, setStartsAt] = useState(shift.startsAt); const [endsAt, setEndsAt] = useState(shift.endsAt);
  useEffect(() => { setStartsAt(shift.startsAt); setEndsAt(shift.endsAt); }, [shift.startsAt, shift.endsAt]);
  if (!editing) return <button className="secondary text-button" onClick={() => setEditing(true)}>Edit times</button>;
  return <form className="time-editor" onSubmit={(event) => { event.preventDefault(); api("/api/shifts", "PATCH", { shiftId: shift.id, startsAt, endsAt }); setEditing(false); }}><label>Actual start<input aria-label="Actual start time" type="time" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /></label><label>Actual end<input aria-label="Actual end time" type="time" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} /></label><button type="submit">Save times</button><button type="button" className="secondary" onClick={() => { setStartsAt(shift.startsAt); setEndsAt(shift.endsAt); setEditing(false); }}>Cancel</button></form>;
}
function PrintRoster({ staff, shifts, dates, payPeriod }: { staff: Staff[]; shifts: Shift[]; dates: string[]; payPeriod: PayPeriod }) { const sortedStaff = [...staff].sort((left, right) => { const leftParts = left.name.trim().split(/\s+/); const rightParts = right.name.trim().split(/\s+/); return `${leftParts[leftParts.length - 1]}, ${left.name}`.localeCompare(`${rightParts[rightParts.length - 1]}, ${right.name}`); }); return <section className="card print-roster"><p className="eyebrow">Manager print roster</p><h2>{readableDate(payPeriod.start)} – {readableDate(payPeriod.end)}</h2><div style={{ overflowX: "auto" }}><table style={{ borderCollapse: "collapse", minWidth: "1100px", width: "100%", fontSize: "12px" }}><thead><tr><th style={{ textAlign: "left", border: "1px solid #dbe2ea", padding: "8px", minWidth: "170px" }}>Employee</th>{dates.map((date) => <th key={date} style={{ border: "1px solid #dbe2ea", padding: "8px", minWidth: "72px" }}>{readableDate(date)}</th>)}</tr></thead><tbody>{sortedStaff.map((person) => <tr key={person.id}><th style={{ textAlign: "left", border: "1px solid #dbe2ea", padding: "8px", background: "#f4f7fb" }}>{person.name}</th>{dates.map((date) => { const assignments = shifts.filter((shift) => shift.date === date && shift.assignee.split(", ").includes(person.name)); return <td key={date} style={{ verticalAlign: "top", border: "1px solid #dbe2ea", padding: "6px" }}>{assignments.map((shift) => <div key={shift.id}><strong>{shift.title}</strong><br />{shift.startsAt}–{shift.endsAt}</div>)}</td>; })}</tr>)}</tbody></table></div></section> }
function ShiftForm({ staff, onSubmit }: { staff: Staff[]; onSubmit: (body: Record<string, string>) => void }) { const [open, setOpen] = useState(false); const [form, setForm] = useState({ date: new Date().toISOString().slice(0, 10), title: "", startsAt: "05:45", endsAt: "10:45", staffId: "" }); if (!open) return <button className="secondary" onClick={() => setOpen(true)}>Add non-standard shift</button>; return <form className="inline-form" onSubmit={(event) => { event.preventDefault(); onSubmit(form); setOpen(false); }}><input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} required/><input placeholder="Shift name" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required/><input type="time" value={form.startsAt} onChange={(event) => setForm({ ...form, startsAt: event.target.value })}/><input type="time" value={form.endsAt} onChange={(event) => setForm({ ...form, endsAt: event.target.value })}/><select value={form.staffId} onChange={(event) => setForm({ ...form, staffId: event.target.value })}><option value="">Post as open</option>{staff.map((person) => <option value={person.id} key={person.id}>{person.name}</option>)}</select><button type="submit">Save</button><button type="button" className="secondary" onClick={() => setOpen(false)}>Cancel</button></form> }
function Directory({ data, api }: { data: Snapshot; api: (path: string, method: string, body?: unknown) => Promise<void> }) {
  const [name, setName] = useState(data.viewer.name);
  const [phone, setPhone] = useState(data.viewer.phone ?? "");
  useEffect(() => setName(data.viewer.name), [data.viewer.name]);
  useEffect(() => setPhone(data.viewer.phone ?? ""), [data.viewer.phone]);
  const manager = data.viewer.role === "manager";
  return <section className="directory-layout">
    <article className="card profile-card"><p className="eyebrow">My profile</p><h2>Your staff profile</h2><p className="muted">Choose the name shown on schedules and in the Staff list. Your email comes from your sign-in account.</p>
      <form className="form-stack" onSubmit={(event) => { event.preventDefault(); api("/api/staff", "PATCH", { action: "updateProfile", name, phone }); }}>
        <label>Displayed name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="First and last name" aria-label="Displayed name" required /></label>
        <label>Email<input value={data.viewer.email} readOnly aria-label="Email" /></label>
        <label>Phone number<input type="tel" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="(555) 555-5555" aria-label="Phone number" required /></label>
        <button type="submit">Save profile</button>
      </form>
    </article>
    <article className="card"><p className="eyebrow">Employee list</p><h2>Your aquatics team</h2><p className="muted">Contact details are visible only to signed-in aquatics staff.</p><div className="directory">{data.staff.map((person) => <div className="person directory-person" key={person.id}><span className="avatar">{person.name.split(" ").map((word) => word[0]).join("")}</span><div><strong>{person.name}</strong><span>{person.role === "manager" ? "Manager" : "Lifeguard"}</span><a href={`mailto:${person.email}`}>{person.email}</a><a href={person.phone ? `tel:${person.phone.replace(/[^+\d]/g, "")}` : undefined} className={person.phone ? "" : "missing-contact"}>{person.phone || "Phone not added yet"}</a></div>{manager && person.role === "staff" && <button className="danger small-button" onClick={() => { if (window.confirm(`Remove ${person.name} from the active employee list? Their scheduling records will be kept.`)) api("/api/staff", "PATCH", { action: "deactivate", staffId: person.id }); }}>Remove</button>}</div>)}</div></article>
  </section>
}
function Availability({ data, api }: { data: Snapshot; api: (path: string, method: string, body?: unknown) => Promise<void> }) { const [form, setForm] = useState({ startsOn: new Date().toISOString().slice(0, 10), endsOn: new Date().toISOString().slice(0, 10), status: "unavailable", note: "" }); return <section className="two-col"><form className="card form-stack" onSubmit={(event) => { event.preventDefault(); api("/api/availability", "POST", form); }}><p className="eyebrow">Staff availability</p><h2>Share your schedule</h2><label>From<input type="date" value={form.startsOn} onChange={(event) => setForm({ ...form, startsOn: event.target.value })}/></label><label>Through<input type="date" value={form.endsOn} onChange={(event) => setForm({ ...form, endsOn: event.target.value })}/></label><label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="unavailable">Unavailable</option><option value="available">Available</option><option value="preferred">Preferred</option></select></label><label>Note<textarea value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} placeholder="Optional details for managers"/></label><button>Save availability</button></form><article className="card"><p className="eyebrow">Team visibility</p><h2>Recent availability</h2>{data.availability.map((item) => <p className="list-item" key={`${item.staff}-${item.note}`}><strong>{item.staff}</strong><span>{item.note}</span></p>)}</article></section> }
function OpenShifts({ shifts, api }: { shifts: Shift[]; api: (path: string, method: string, body?: unknown) => Promise<void> }) { return <section className="card"><p className="eyebrow">Open shifts</p><h2>Coverage opportunities</h2>{shifts.length ? shifts.map((shift) => <div className="request" key={shift.id}><div><strong>{shift.title} · {readableDate(shift.date)}</strong><span>{shift.startsAt}–{shift.endsAt} · {duration(shift.startsAt, shift.endsAt)} hrs</span></div><button onClick={() => api(`/api/open-shifts/${shift.id}/claim`, "POST")}>Claim shift</button></div>) : <p className="muted">No open shifts right now.</p>}</section> }
function Swaps({ data, api }: { data: Snapshot; api: (path: string, method: string, body?: unknown) => Promise<void> }) { return <section className="card"><p className="eyebrow">Shift swaps</p><h2>Requests awaiting review</h2>{data.swaps.length ? data.swaps.map((swap) => <div className="request" key={swap.id}><div><strong>{swap.requester} → {swap.recipient}</strong><span>{swap.shift}</span></div>{data.viewer.role === "manager" && <div><button onClick={() => api(`/api/swaps/${swap.id}`, "PATCH", { action: "approve" })}>Approve</button><button className="secondary" onClick={() => api(`/api/swaps/${swap.id}`, "PATCH", { action: "decline" })}>Decline</button></div>}</div>) : <p className="muted">No swap requests are pending.</p>}<p className="muted footnote">Staff can submit swaps for an assigned shift; managers make the final approval.</p></section> }
function Hours({ data, scheduledHours }: { data: Snapshot; scheduledHours: number }) { const totals = new Map<string, number>(); data.shifts.forEach((shift) => shift.assignee === "Open" ? undefined : shift.assignee.split(", ").forEach((name) => totals.set(name, (totals.get(name) ?? 0) + duration(shift.startsAt, shift.endsAt)))); return <section className="card"><p className="eyebrow">Pay period tracking</p><h2>Scheduled hours</h2><p className="muted">{readableDate(data.payPeriod.start)} through {readableDate(data.payPeriod.end)} · timesheets due {readableDate(data.payPeriod.dueDate)}.</p><div className="hours-total"><strong>{scheduledHours} hrs</strong><span>team total this pay period</span></div>{Array.from(totals.entries()).map(([name, hours]) => <div className="hours-row" key={name}><span>{name}</span><strong>{hours} hrs</strong></div>)}</section> }
