"use client";

import { useEffect, useMemo, useState } from "react";

type Staff = { id: string; name: string; role: string; active: boolean };
type Shift = { id: string; date: string; title: string; startsAt: string; endsAt: string; assignee: string; status: string };
type PayPeriod = { start: string; end: string; dueDate: string; defaultDueDate: string };
type Snapshot = { demo: boolean; viewer: { name: string; role: string }; staff: Staff[]; shifts: Shift[]; swaps: { id: string; requester: string; shift: string; recipient: string; status: string }[]; availability: { staff: string; note: string }[]; payPeriod: PayPeriod };

const tabs = ["Dashboard", "Schedule", "Directory", "Availability", "Open shifts", "Swaps", "Hours"] as const;
type Tab = (typeof tabs)[number];

function readableDate(date: string) { return new Intl.DateTimeFormat(undefined, { weekday: "short", month: "short", day: "numeric" }).format(new Date(`${date}T12:00:00`)); }
function readableLongDate(date: string) { return new Intl.DateTimeFormat(undefined, { weekday: "long", month: "long", day: "numeric" }).format(new Date(`${date}T12:00:00`)); }
function duration(start: string, end: string) { const [a, b] = [start, end].map((value) => { const [hour, minute] = value.split(":").map(Number); return hour + minute / 60; }); return Math.max(0, b - a); }

export default function Scheduler() {
  const [tab, setTab] = useState<Tab>("Dashboard"); const [data, setData] = useState<Snapshot | null>(null); const [notice, setNotice] = useState("");
  const refresh = () => fetch("/api/schedule").then((res) => res.json()).then((body) => setData(body)).catch(() => setNotice("Could not load the schedule."));
  useEffect(() => { refresh(); }, []);
  const openShifts = data?.shifts.filter((shift) => shift.status === "open") ?? [];
  const scheduledHours = useMemo(() => (data?.shifts ?? []).filter((shift) => shift.assignee !== "Open").reduce((total, shift) => total + duration(shift.startsAt, shift.endsAt), 0), [data]);
  async function api(path: string, method: string, body?: unknown) {
    if (data?.demo) { setNotice("Preview mode: sign in to save this change."); return; }
    const response = await fetch(path, { method, headers: { "content-type": "application/json" }, body: body ? JSON.stringify(body) : undefined });
    const payload = await response.json(); setNotice(payload.error || payload.message || (payload.ok ? "Saved." : "Something went wrong.")); if (payload.ok) refresh();
  }
  if (!data) return <main className="loading">Loading the schedule…</main>;
  return <main>
    <header><div className="topbar"><div><strong>Seal Beach Aquatics Schedule</strong><span>{data.demo ? "Interactive preview" : `${data.viewer.role} view`}</span></div><a href="/sign-in">Sign in</a></div></header>
    <section className="wrap"><div className="title-row"><div><p className="eyebrow">Operations center</p><h1>Clear coverage, calmer days.</h1><p className="muted">Plan the pay period, coordinate changes, and keep every lifeguard in the loop.</p></div>{data.demo && <div className="preview-note">Sign in to use the secure staff schedule and save changes.</div>}</div>
      <nav className="tabs" aria-label="Scheduling areas">{tabs.map((item) => <button key={item} className={tab === item ? "tab active" : "tab"} onClick={() => setTab(item)}>{item}</button>)}</nav>
      {notice && <p className="notice">{notice}<button onClick={() => setNotice("")} aria-label="Dismiss">×</button></p>}
      {tab === "Dashboard" && <Dashboard data={data} openCount={openShifts.length} hours={scheduledHours} setTab={setTab} api={api} />}
      {tab === "Schedule" && <Schedule data={data} api={api} />}
      {tab === "Directory" && <Directory staff={data.staff} />}
      {tab === "Availability" && <Availability data={data} api={api} />}
      {tab === "Open shifts" && <OpenShifts shifts={openShifts} api={api} />}
      {tab === "Swaps" && <Swaps data={data} api={api} />}
      {tab === "Hours" && <Hours data={data} scheduledHours={scheduledHours} />}
    </section>
  </main>;
}

function Dashboard({ data, openCount, hours, setTab, api }: { data: Snapshot; openCount: number; hours: number; setTab: (tab: Tab) => void; api: (path: string, method: string, body?: unknown) => Promise<void> }) { return <><div className="metrics"><Metric label="Active staff" value={data.staff.length} /><Metric label="Open shifts" value={openCount} /><Metric label="Pending swaps" value={data.swaps.filter((item) => item.status === "pending").length} /><Metric label="Scheduled this pay period" value={`${hours} hrs`} /></div><section className="card pay-period-card"><div><p className="eyebrow">Current pay period</p><h2>{readableDate(data.payPeriod.start)} – {readableDate(data.payPeriod.end)}</h2><p className="muted">Two weeks, Sunday through Saturday. Scheduled hours and coverage include the entire pay period.</p></div><div className="due-date"><span>Timesheets due</span><strong>{readableLongDate(data.payPeriod.dueDate)}</strong>{data.payPeriod.dueDate !== data.payPeriod.defaultDueDate && <em>Manager-adjusted deadline</em>}{data.viewer.role === "manager" && <DueDateForm payPeriod={data.payPeriod} api={api} />}</div></section><section className="card action-card"><div><p className="eyebrow">Manager dashboard</p><h2>Pay period at a glance</h2><p className="muted">Review coverage gaps, availability conflicts, and staff requests from one place.</p></div><button onClick={() => setTab("Schedule")}>Open schedule builder</button></section><section className="two-col"><article className="card"><h2>Needs attention</h2>{openCount ? <p>{openCount} open shift{openCount === 1 ? "" : "s"} still need coverage.</p> : <p>All scheduled shifts are covered.</p>}<button className="secondary" onClick={() => setTab("Open shifts")}>Review open shifts</button></article><article className="card"><h2>Availability notes</h2>{data.availability.map((item) => <p className="list-item" key={`${item.staff}-${item.note}`}><strong>{item.staff}</strong><span>{item.note}</span></p>)}</article></section></> }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="metric card"><span>{label}</span><strong>{value}</strong></div>; }
function DueDateForm({ payPeriod, api }: { payPeriod: PayPeriod; api: (path: string, method: string, body?: unknown) => Promise<void> }) { const [editing, setEditing] = useState(false); const [dueDate, setDueDate] = useState(payPeriod.dueDate); useEffect(() => setDueDate(payPeriod.dueDate), [payPeriod.dueDate]); if (!editing) return <button className="secondary small-button" onClick={() => setEditing(true)}>Change deadline</button>; return <form className="due-date-form" onSubmit={(event) => { event.preventDefault(); api("/api/pay-period", "PATCH", { dueDate }); setEditing(false); }}><label>Due date<input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} required /></label><button type="submit" className="small-button">Save</button><button type="button" className="secondary small-button" onClick={() => { setDueDate(payPeriod.dueDate); setEditing(false); }}>Cancel</button></form> }
function Schedule({ data, api }: { data: Snapshot; api: (path: string, method: string, body?: unknown) => Promise<void> }) { const byDate = Object.groupBy(data.shifts, (shift) => shift.date); const dates = Array.from({ length: 14 }, (_, index) => { const date = new Date(`${data.payPeriod.start}T12:00:00`); date.setDate(date.getDate() + index); return date.toISOString().slice(0, 10); }); return <><section className="card schedule-head"><div><p className="eyebrow">Manager schedule builder</p><h2>Pay-period schedule</h2><p className="muted">{readableDate(data.payPeriod.start)} through {readableDate(data.payPeriod.end)} · Sunday–Saturday, two-week period.</p></div><ShiftForm staff={data.staff} onSubmit={(body) => api("/api/shifts", "POST", body)} /></section><section className="schedule-grid">{dates.map((date) => <article className="day card" key={date}><h3>{readableDate(date)}</h3>{(byDate[date] ?? []).map((shift) => <div className={shift.status === "open" ? "shift open" : "shift"} key={shift.id}><strong>{shift.title}</strong><span>{shift.startsAt}–{shift.endsAt} · {duration(shift.startsAt, shift.endsAt)} hrs</span><b>{shift.assignee}</b>{shift.status === "open" && <button className="secondary" onClick={() => api(`/api/open-shifts/${shift.id}/claim`, "POST")}>Claim shift</button>}</div>)}</article>)}</section></> }
function ShiftForm({ staff, onSubmit }: { staff: Staff[]; onSubmit: (body: Record<string, string>) => void }) { const [open, setOpen] = useState(false); const [form, setForm] = useState({ date: new Date().toISOString().slice(0, 10), title: "", startsAt: "05:45", endsAt: "10:45", staffId: "" }); if (!open) return <button onClick={() => setOpen(true)}>Add shift</button>; return <form className="inline-form" onSubmit={(event) => { event.preventDefault(); onSubmit(form); setOpen(false); }}><input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} required/><input placeholder="Shift name" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required/><input type="time" value={form.startsAt} onChange={(event) => setForm({ ...form, startsAt: event.target.value })}/><input type="time" value={form.endsAt} onChange={(event) => setForm({ ...form, endsAt: event.target.value })}/><select value={form.staffId} onChange={(event) => setForm({ ...form, staffId: event.target.value })}><option value="">Post as open</option>{staff.map((person) => <option value={person.id} key={person.id}>{person.name}</option>)}</select><button type="submit">Save</button><button type="button" className="secondary" onClick={() => setOpen(false)}>Cancel</button></form> }
function Directory({ staff }: { staff: Staff[] }) { return <section className="card"><p className="eyebrow">Staff directory</p><h2>Your aquatics team</h2><div className="directory">{staff.map((person) => <div className="person" key={person.id}><span className="avatar">{person.name.split(" ").map((word) => word[0]).join("")}</span><div><strong>{person.name}</strong><span>{person.role === "manager" ? "Manager" : "Lifeguard"}</span></div><em>{person.active ? "Active" : "Inactive"}</em></div>)}</div></section> }
function Availability({ data, api }: { data: Snapshot; api: (path: string, method: string, body?: unknown) => Promise<void> }) { const [form, setForm] = useState({ startsOn: new Date().toISOString().slice(0, 10), endsOn: new Date().toISOString().slice(0, 10), status: "unavailable", note: "" }); return <section className="two-col"><form className="card form-stack" onSubmit={(event) => { event.preventDefault(); api("/api/availability", "POST", form); }}><p className="eyebrow">Staff availability</p><h2>Share your schedule</h2><label>From<input type="date" value={form.startsOn} onChange={(event) => setForm({ ...form, startsOn: event.target.value })}/></label><label>Through<input type="date" value={form.endsOn} onChange={(event) => setForm({ ...form, endsOn: event.target.value })}/></label><label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="unavailable">Unavailable</option><option value="available">Available</option><option value="preferred">Preferred</option></select></label><label>Note<textarea value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} placeholder="Optional details for managers"/></label><button>Save availability</button></form><article className="card"><p className="eyebrow">Team visibility</p><h2>Recent availability</h2>{data.availability.map((item) => <p className="list-item" key={`${item.staff}-${item.note}`}><strong>{item.staff}</strong><span>{item.note}</span></p>)}</article></section> }
function OpenShifts({ shifts, api }: { shifts: Shift[]; api: (path: string, method: string, body?: unknown) => Promise<void> }) { return <section className="card"><p className="eyebrow">Open shifts</p><h2>Coverage opportunities</h2>{shifts.length ? shifts.map((shift) => <div className="request" key={shift.id}><div><strong>{shift.title} · {readableDate(shift.date)}</strong><span>{shift.startsAt}–{shift.endsAt} · {duration(shift.startsAt, shift.endsAt)} hrs</span></div><button onClick={() => api(`/api/open-shifts/${shift.id}/claim`, "POST")}>Claim shift</button></div>) : <p className="muted">No open shifts right now.</p>}</section> }
function Swaps({ data, api }: { data: Snapshot; api: (path: string, method: string, body?: unknown) => Promise<void> }) { return <section className="card"><p className="eyebrow">Shift swaps</p><h2>Requests awaiting review</h2>{data.swaps.length ? data.swaps.map((swap) => <div className="request" key={swap.id}><div><strong>{swap.requester} → {swap.recipient}</strong><span>{swap.shift}</span></div>{data.viewer.role === "manager" && <div><button onClick={() => api(`/api/swaps/${swap.id}`, "PATCH", { action: "approve" })}>Approve</button><button className="secondary" onClick={() => api(`/api/swaps/${swap.id}`, "PATCH", { action: "decline" })}>Decline</button></div>}</div>) : <p className="muted">No swap requests are pending.</p>}<p className="muted footnote">Staff can submit swaps for an assigned shift; managers make the final approval.</p></section> }
function Hours({ data, scheduledHours }: { data: Snapshot; scheduledHours: number }) { const entries = Object.entries(Object.groupBy(data.shifts.filter((shift) => shift.assignee !== "Open"), (shift) => shift.assignee)); return <section className="card"><p className="eyebrow">Pay period tracking</p><h2>Scheduled hours</h2><p className="muted">{readableDate(data.payPeriod.start)} through {readableDate(data.payPeriod.end)} · timesheets due {readableDate(data.payPeriod.dueDate)}.</p><div className="hours-total"><strong>{scheduledHours} hrs</strong><span>team total this pay period</span></div>{entries.map(([name, shifts]) => <div className="hours-row" key={name}><span>{name}</span><strong>{(shifts ?? []).reduce((total, shift) => total + duration(shift.startsAt, shift.endsAt), 0)} hrs</strong></div>)}</section> }
